import type { AnalyticsModule } from 'src/modules/analytics';
import type { BaseModule } from '../modules/base';
import type { ErrorHandlerModule } from '../modules/errorHandler';
import type { GraphqlModule } from '../modules/graphql';
import type { HostModule } from '../modules/host';
import type { SessionModule } from '../modules/session';
import type { OpenApiModule } from '../modules/openapi';
import type { RouterModule } from '../modules/router';
import type { StoreConfigModule } from '../modules/storeConfig';
import type { StoreTokenModule } from '../modules/storeToken';
import type { StoreUserModule } from '../modules/storeUser';
import type { StoreSessionModule } from '../modules/storeSession';
import type { StoreTrackModule } from '../modules/storeTrack';
import type { StorePlaylistModule } from '../modules/storePlaylist';
import type { OAuthModule } from '../modules/oauth';
import type { OAuthGoogleModule } from '../modules/oauthGoogle';
import type { OAuthFacebookModule } from '../modules/oauthFacebook';
import type { OAuthSpotifyModule } from '../modules/oauthSpotify';
import type { OAuthStravaModule } from '../modules/oauthStrava';
import type { StravaModule } from '../modules/strava';
import type { SpotifyModule } from '../modules/spotify';
import type { SpotifyHistoryModule } from '../modules/spotifyHistory';
import type { StravaWebhookModule } from '../modules/stravaWebhook';
import type { StravaSpotifyModule } from '../modules/stravaSpotify';
import type { ServerModuleName } from '.';

type AppServerModules = {
  [ServerModuleName.ANALYTICS]: AnalyticsModule;
  [ServerModuleName.BASE]: BaseModule;
  [ServerModuleName.ERR_HANDLER]: ErrorHandlerModule;
  [ServerModuleName.HOST]: HostModule;
  [ServerModuleName.GRAPHQL]: GraphqlModule;
  [ServerModuleName.OAUTH]: OAuthModule;
  [ServerModuleName.OAUTH_GOOGLE]: OAuthGoogleModule;
  [ServerModuleName.OAUTH_FACEBOOK]: OAuthFacebookModule;
  [ServerModuleName.OAUTH_SPOTIFY]: OAuthSpotifyModule;
  [ServerModuleName.OAUTH_STRAVA]: OAuthStravaModule;
  [ServerModuleName.OPENAPI]: OpenApiModule;
  [ServerModuleName.ROUTER]: RouterModule;
  [ServerModuleName.SESSION]: SessionModule;
  [ServerModuleName.SPOTIFY]: SpotifyModule;
  [ServerModuleName.SPOTIFY_HISTORY]: SpotifyHistoryModule;
  [ServerModuleName.STORE_PLAYLIST]: StorePlaylistModule;
  [ServerModuleName.STORE_CONFIG]: StoreConfigModule;
  [ServerModuleName.STORE_TOKEN]: StoreTokenModule;
  [ServerModuleName.STORE_TRACK]: StoreTrackModule;
  [ServerModuleName.STORE_USER]: StoreUserModule;
  [ServerModuleName.STORE_SESSION]: StoreSessionModule;
  [ServerModuleName.STRAVA]: StravaModule;
  [ServerModuleName.STRAVA_WEBHOOK]: StravaWebhookModule;
  [ServerModuleName.STRAVA_SPOTIFY]: StravaSpotifyModule;
};

export default AppServerModules;
