import type { AnalyticsModule } from '../modules/analytics';
import type { BaseModule } from '../modules/base';
import type { ErrorHandlerModule } from '../modules/errorHandler';
import type { GraphqlModule } from '../modules/graphql';
import type { HostModule } from '../modules/host';
import type { SessionModule } from '../modules/session';
import type { OpenApiModule } from '../modules/openapi';
import type { RouterModule } from '../modules/router';
import type { PrismaModule } from '../modules/prisma';
import type { StoreConfigModule } from '../modules/storeConfig';
import type { StoreTokenModule } from '../modules/storeToken';
import type { StoreUserModule } from '../modules/storeUser';
import type { StoreSessionModule } from '../modules/storeSession';
import type { StoreTrackModule } from '../modules/storeTrack';
import type { StorePlaylistModule } from '../modules/storePlaylist';
import type { OAuthModule } from '../modules/oauth';
import type { OAuthAppleMusicModule } from '../modules/oauthAppleMusic';
import type { OAuthFacebookModule } from '../modules/oauthFacebook';
import type { OAuthGoogleModule } from '../modules/oauthGoogle';
import type { OAuthSpotifyModule } from '../modules/oauthSpotify';
import type { OAuthStravaModule } from '../modules/oauthStrava';
import type { ApiStravaModule } from '../modules/apiStrava';
import type { ApiSpotifyModule } from '../modules/apiSpotify';
import type { PlaylistAppleModule } from '../modules/playlistApple';
import type { PlaylistSpotifyModule } from '../modules/playlistSpotify';
import type { TrackHistoryModule } from '../modules/trackHistory';
import type { StravaWebhookModule } from '../modules/stravaWebhook';
import type { PlaylistModule } from '../modules/playlist';
import type { ServerModuleName } from './index';

type AppServerModules = {
  [ServerModuleName.ANALYTICS]: AnalyticsModule;
  [ServerModuleName.API_SPOTIFY]: ApiSpotifyModule;
  [ServerModuleName.API_STRAVA]: ApiStravaModule;
  [ServerModuleName.BASE]: BaseModule;
  [ServerModuleName.ERR_HANDLER]: ErrorHandlerModule;
  [ServerModuleName.HOST]: HostModule;
  [ServerModuleName.GRAPHQL]: GraphqlModule;
  [ServerModuleName.OAUTH]: OAuthModule;
  [ServerModuleName.OAUTH_APPLE_MUSIC]: OAuthAppleMusicModule;
  [ServerModuleName.OAUTH_FACEBOOK]: OAuthFacebookModule;
  [ServerModuleName.OAUTH_GOOGLE]: OAuthGoogleModule;
  [ServerModuleName.OAUTH_SPOTIFY]: OAuthSpotifyModule;
  [ServerModuleName.OAUTH_STRAVA]: OAuthStravaModule;
  [ServerModuleName.OPENAPI]: OpenApiModule;
  [ServerModuleName.PLAYLIST]: PlaylistModule;
  [ServerModuleName.PLAYLIST_APPLE]: PlaylistAppleModule;
  [ServerModuleName.PLAYLIST_SPOTIFY]: PlaylistSpotifyModule;
  [ServerModuleName.PRISMA]: PrismaModule;
  [ServerModuleName.ROUTER]: RouterModule;
  [ServerModuleName.SESSION]: SessionModule;
  [ServerModuleName.TRACK_HISTORY]: TrackHistoryModule;
  [ServerModuleName.STORE_PLAYLIST]: StorePlaylistModule;
  [ServerModuleName.STORE_CONFIG]: StoreConfigModule;
  [ServerModuleName.STORE_TOKEN]: StoreTokenModule;
  [ServerModuleName.STORE_TRACK]: StoreTrackModule;
  [ServerModuleName.STORE_USER]: StoreUserModule;
  [ServerModuleName.STORE_SESSION]: StoreSessionModule;
  [ServerModuleName.STRAVA_WEBHOOK]: StravaWebhookModule;
};

export default AppServerModules;
