/* eslint-disable */
/* This file is autogenerated, see codegen.composables.yml */

import type { AnyServerModules } from '../lib/ServerModule';

/**
 * Context available in ResolverContext
 *
 * To extend this interface, use:
 * @example
 * declare module './path/to/graphql.d.ts' {
 *   interface ResolverContext<TModules extends AnyServerModules = AnyServerModules> 
 *     extends MyExtendingInterface {
 *     // Define additional props here
 *   }
 * }
 */
export interface ResolverContext<TModules extends AnyServerModules = AnyServerModules> {}

import type { AuthProvider } from './src/types/index';
import type { ActivityProvider } from './src/types/index';
import type { PlaylistProvider } from './src/types/index';
import type { GraphQLResolveInfo } from 'graphql';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type RequireFields<T, K extends keyof T> = { [X in Exclude<keyof T, K>]?: T[X] } & { [P in K]-?: NonNullable<T[P]> };
export type EnumResolverSignature<T, AllowedValues = any> = { [key in keyof T]?: AllowedValues };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type GqlQuery = {
  __typename?: 'Query';
  getAllProviders: Array<GqlProvider>;
  getCurrentUser: GqlUser;
  getCurrentUserConfig: GqlUserConfig;
  getCurrentUserPlaylists: Array<GqlPlaylist>;
  hello?: Maybe<Scalars['String']>;
};

export type GqlMutation = {
  __typename?: 'Mutation';
  deleteCurrentUser: GqlUser;
  deleteCurrentUserProviders: Array<Maybe<GqlProvider>>;
  hello?: Maybe<Scalars['String']>;
  logoutCurrentUser: GqlUser;
  updateCurrentUserConfig: GqlUserConfig;
};


export type GqlMutationDeleteCurrentUserProvidersArgs = {
  providerIds: Array<Scalars['String']>;
};


export type GqlMutationUpdateCurrentUserConfigArgs = {
  userConfigInput: GqlUserConfigInput;
};

export type GqlProvider = {
  __typename?: 'Provider';
  providerId: Scalars['String'];
  name: Scalars['String'];
  isAuthProvider: Scalars['Boolean'];
  isActivityProvider: Scalars['Boolean'];
  isPlaylistProvider: Scalars['Boolean'];
};

export { AuthProvider };

export { PlaylistProvider };

export { ActivityProvider };

export type GqlUserConfig = {
  __typename?: 'UserConfig';
  /** Whether user playlists should be created as collaborative */
  playlistCollaborative: Scalars['Boolean'];
  /** Whether user playlists should be created as public */
  playlistPublic: Scalars['Boolean'];
  /** Whether user playlists should be created automatically */
  playlistAutoCreate: Scalars['Boolean'];
  /** Template for creating playlist description */
  playlistDescriptionTemplate?: Maybe<Scalars['String']>;
  /** Template for creating playlist title */
  playlistTitleTemplate?: Maybe<Scalars['String']>;
  /** Whether activity description should be updated after playlist is created */
  activityDescriptionEnabled: Scalars['Boolean'];
  /** Template for creating updated activity description that includes playlist */
  activityDescriptionTemplate?: Maybe<Scalars['String']>;
};

export type GqlUserConfigInput = {
  /** Whether user playlists should be created as collaborative */
  playlistCollaborative?: Maybe<Scalars['Boolean']>;
  /** Whether user playlists should be created as public */
  playlistPublic?: Maybe<Scalars['Boolean']>;
  /** Whether user playlists should be created automatically */
  playlistAutoCreate?: Maybe<Scalars['Boolean']>;
  /** Template for creating playlist description */
  playlistDescriptionTemplate?: Maybe<Scalars['String']>;
  /** Template for creating playlist title */
  playlistTitleTemplate?: Maybe<Scalars['String']>;
  /** Whether activity description should be updated after playlist is created */
  activityDescriptionEnabled?: Maybe<Scalars['Boolean']>;
  /** Template for creating updated activity description that includes playlist */
  activityDescriptionTemplate?: Maybe<Scalars['String']>;
};

export type GqlPlaylist = {
  __typename?: 'Playlist';
  playlistProviderId: Scalars['String'];
  playlistId: Scalars['String'];
  playlistUrl?: Maybe<Scalars['String']>;
  playlistName?: Maybe<Scalars['String']>;
  activityProviderId: Scalars['String'];
  activityId: Scalars['String'];
  activityName?: Maybe<Scalars['String']>;
  activityUrl?: Maybe<Scalars['String']>;
  dateCreated?: Maybe<Scalars['Int']>;
};

export type GqlUser = {
  __typename?: 'User';
  userId: Scalars['String'];
  email?: Maybe<Scalars['String']>;
  nameFamily?: Maybe<Scalars['String']>;
  nameGiven?: Maybe<Scalars['String']>;
  nameDisplay?: Maybe<Scalars['String']>;
  photo?: Maybe<Scalars['String']>;
  providers: Array<GqlProvider>;
};



export type ResolverTypeWrapper<T> = Promise<T> | T;


export type LegacyStitchingResolver<TResult, TParent, TContext, TArgs> = {
  fragment: string;
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};

export type NewStitchingResolver<TResult, TParent, TContext, TArgs> = {
  selectionSet: string;
  resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type StitchingResolver<TResult, TParent, TContext, TArgs> = LegacyStitchingResolver<TResult, TParent, TContext, TArgs> | NewStitchingResolver<TResult, TParent, TContext, TArgs>;
export type Resolver<TResult, TParent = {}, TContext = {}, TArgs = {}> =
  | ResolverFn<TResult, TParent, TContext, TArgs>
  | StitchingResolver<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => AsyncIterator<TResult> | Promise<AsyncIterator<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<TResult, TKey extends string, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
  resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
  subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
  resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<TResult, TKey extends string, TParent = {}, TContext = {}, TArgs = {}> =
  | ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
  | SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<TTypes, TParent = {}, TContext = {}> = (
  parent: TParent,
  context: TContext,
  info?: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<T = {}, TContext = {}> = (obj: T, context: TContext, info?: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<TResult = {}, TParent = {}, TContext = {}, TArgs = {}> = (
  next: NextResolverFn<TResult>,
  parent: TParent,
  args: TArgs,
  context: TContext,
  info?: GraphQLResolveInfo
) => TResult | Promise<TResult>;

/** Mapping between all available schema types and the resolvers types */
export type GqlResolversTypes = {
  Query: ResolverTypeWrapper<{}>;
  String: ResolverTypeWrapper<Partial<Scalars['String']>>;
  Mutation: ResolverTypeWrapper<{}>;
  Provider: ResolverTypeWrapper<Partial<GqlProvider>>;
  Boolean: ResolverTypeWrapper<Partial<Scalars['Boolean']>>;
  AuthProvider: ResolverTypeWrapper<Partial<AuthProvider>>;
  PlaylistProvider: ResolverTypeWrapper<Partial<PlaylistProvider>>;
  ActivityProvider: ResolverTypeWrapper<Partial<ActivityProvider>>;
  UserConfig: ResolverTypeWrapper<Partial<GqlUserConfig>>;
  UserConfigInput: ResolverTypeWrapper<Partial<GqlUserConfigInput>>;
  Playlist: ResolverTypeWrapper<Partial<GqlPlaylist>>;
  Int: ResolverTypeWrapper<Partial<Scalars['Int']>>;
  User: ResolverTypeWrapper<Partial<GqlUser>>;
};

/** Mapping between all available schema types and the resolvers parents */
export type GqlResolversParentTypes = {
  Query: {};
  String: Partial<Scalars['String']>;
  Mutation: {};
  Provider: Partial<GqlProvider>;
  Boolean: Partial<Scalars['Boolean']>;
  UserConfig: Partial<GqlUserConfig>;
  UserConfigInput: Partial<GqlUserConfigInput>;
  Playlist: Partial<GqlPlaylist>;
  Int: Partial<Scalars['Int']>;
  User: Partial<GqlUser>;
};

export type GqlQueryResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['Query'] = GqlResolversParentTypes['Query']> = {
  getAllProviders?: Resolver<Array<GqlResolversTypes['Provider']>, ParentType, ContextType>;
  getCurrentUser?: Resolver<GqlResolversTypes['User'], ParentType, ContextType>;
  getCurrentUserConfig?: Resolver<GqlResolversTypes['UserConfig'], ParentType, ContextType>;
  getCurrentUserPlaylists?: Resolver<Array<GqlResolversTypes['Playlist']>, ParentType, ContextType>;
  hello?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
};

export type GqlMutationResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['Mutation'] = GqlResolversParentTypes['Mutation']> = {
  deleteCurrentUser?: Resolver<GqlResolversTypes['User'], ParentType, ContextType>;
  deleteCurrentUserProviders?: Resolver<Array<Maybe<GqlResolversTypes['Provider']>>, ParentType, ContextType, RequireFields<GqlMutationDeleteCurrentUserProvidersArgs, 'providerIds'>>;
  hello?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  logoutCurrentUser?: Resolver<GqlResolversTypes['User'], ParentType, ContextType>;
  updateCurrentUserConfig?: Resolver<GqlResolversTypes['UserConfig'], ParentType, ContextType, RequireFields<GqlMutationUpdateCurrentUserConfigArgs, 'userConfigInput'>>;
};

export type GqlProviderResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['Provider'] = GqlResolversParentTypes['Provider']> = {
  providerId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  name?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  isAuthProvider?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  isActivityProvider?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  isPlaylistProvider?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type GqlAuthProviderResolvers = EnumResolverSignature<{ FACEBOOK?: any, GOOGLE?: any }, GqlResolversTypes['AuthProvider']>;

export type GqlPlaylistProviderResolvers = EnumResolverSignature<{ SPOTIFY?: any, APPLE_MUSIC?: any }, GqlResolversTypes['PlaylistProvider']>;

export type GqlActivityProviderResolvers = EnumResolverSignature<{ STRAVA?: any }, GqlResolversTypes['ActivityProvider']>;

export type GqlUserConfigResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['UserConfig'] = GqlResolversParentTypes['UserConfig']> = {
  playlistCollaborative?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  playlistPublic?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  playlistAutoCreate?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  playlistDescriptionTemplate?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  playlistTitleTemplate?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  activityDescriptionEnabled?: Resolver<GqlResolversTypes['Boolean'], ParentType, ContextType>;
  activityDescriptionTemplate?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type GqlPlaylistResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['Playlist'] = GqlResolversParentTypes['Playlist']> = {
  playlistProviderId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  playlistId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  playlistUrl?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  playlistName?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  activityProviderId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  activityId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  activityName?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  activityUrl?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  dateCreated?: Resolver<Maybe<GqlResolversTypes['Int']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type GqlUserResolvers<ContextType = ResolverContext, ParentType extends GqlResolversParentTypes['User'] = GqlResolversParentTypes['User']> = {
  userId?: Resolver<GqlResolversTypes['String'], ParentType, ContextType>;
  email?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  nameFamily?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  nameGiven?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  nameDisplay?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  photo?: Resolver<Maybe<GqlResolversTypes['String']>, ParentType, ContextType>;
  providers?: Resolver<Array<GqlResolversTypes['Provider']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type GqlResolvers<ContextType = ResolverContext> = {
  Query?: GqlQueryResolvers<ContextType>;
  Mutation?: GqlMutationResolvers<ContextType>;
  Provider?: GqlProviderResolvers<ContextType>;
  AuthProvider?: GqlAuthProviderResolvers;
  PlaylistProvider?: GqlPlaylistProviderResolvers;
  ActivityProvider?: GqlActivityProviderResolvers;
  UserConfig?: GqlUserConfigResolvers<ContextType>;
  Playlist?: GqlPlaylistResolvers<ContextType>;
  User?: GqlUserResolvers<ContextType>;
};



// Generated on 2021-03-18T21:00:03+00:00
