# See https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: server/deploy/before_install.sh
      timeout: 1200
      runas: ec2-user
  AfterInstall:
    - location: server/deploy/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: server/deploy/start.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: server/deploy/stop.sh
      timeout: 60
      runas: ec2-user
  # ValidateService:
  # - location: backend/app/deploy/validate.sh
  # timeout: 60
  # runas: ec2-user
