openapi: 3.0.1
info:
  title: moovin-groovin (strava webhook)
  description: Server for integrating Strava API with Music Streaming APIs (Strava Webhook endpoints)
  version: 1.0.0
paths:
  /callback:
    get:
      description: Confirm Strava push subscription
      parameters:
        - name: hub.mode
          in: query
          schema:
            type: string
        - name: hub.challenge
          in: query
          schema:
            type: string
        - name: hub.verify_token
          in: query
          schema:
            type: string
      responses:
        200:
          description: Successfully confirmed
    post:
      responses:
        200:
          description: Returns all examples
          content: {}
