/**
 * Last updated: 2020-01-02
 * Taken from: https://developers.strava.com/docs/reference/#api-models-ActivityType
 */
enum ActivityType {
  ALPINE_SKI = 'AlpineSki',
  BACKCOUNTRY_SKI = 'BackcountrySki',
  CANOEING = 'Canoeing',
  CROSSFIT = 'Crossfit',
  E_BIKE_RIDE = 'EBikeRide',
  ELLIPTICAL = 'Elliptical',
  GOLF = 'Golf',
  HANDCYCLE = 'Handcycle',
  HIKE = 'Hike',
  ICE_SKATE = 'IceSkate',
  INLINE_SKATE = 'InlineSkate',
  KAYAKING = 'Kayaking',
  KITESURF = 'Kitesurf',
  NORDIC_SKI = 'NordicSki',
  RIDE = 'Ride',
  ROCK_CLIMBING = 'RockClimbing',
  ROLLER_SKI = 'RollerSki',
  ROWING = 'Rowing',
  RUN = 'Run',
  SAIL = 'Sail',
  SKATEBOAD = 'Skateboard',
  SNOWBOARD = 'Snowboard',
  SNOWSHOE = 'Snowshoe',
  SOCCER = 'Soccer',
  STAIR_STEPPER = 'StairStepper',
  STAND_UP_PADDLING = 'StandUpPaddling',
  SURFING = 'Surfing',
  SWIM = 'Swim',
  VELOMOBILE = 'Velomobile',
  VIRTUAL_RIDE = 'VirtualRide',
  VIRTUAL_RUN = 'VirtualRun',
  WALK = 'Walk',
  WEIGHT_TRAINING = 'WeightTraining',
  WHEELCHAIR = 'Wheelchair',
  WINDSURF = 'Windsurf',
  WORKOUT = 'Workout',
  YOGA = 'Yoga',
}

export default ActivityType;
