openapi: 3.0.1
info:
  title: strava-spotify-playlist
  description: Server for integrating Strava API with Spotify API
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths: {}
