/* eslint-disable */
/* This file is autogenerated, see codegen.yml */
import gql from 'graphql-tag';
type Maybe<T> = T | null;
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

type Query = {
  __typename?: 'Query';
  getAllProviders: Array<Provider>;
  getCurrentUser: User;
  getCurrentUserConfig: UserConfig;
  getCurrentUserPlaylists: Array<Playlist>;
  hello: Maybe<Scalars['String']>;
};

type Mutation = {
  __typename?: 'Mutation';
  deleteCurrentUser: User;
  deleteCurrentUserProviders: Array<Maybe<Provider>>;
  hello: Maybe<Scalars['String']>;
  logoutCurrentUser: User;
  updateCurrentUserConfig: UserConfig;
};


type MutationdeleteCurrentUserProvidersArgs = {
  providerIds: Array<Scalars['String']>;
};


type MutationupdateCurrentUserConfigArgs = {
  userConfigInput: UserConfigInput;
};

type Provider = {
  __typename?: 'Provider';
  providerId: Scalars['String'];
  name: Scalars['String'];
  isAuthProvider: Scalars['Boolean'];
  isActivityProvider: Scalars['Boolean'];
  isPlaylistProvider: Scalars['Boolean'];
};

type AuthProvider = 
  | 'FACEBOOK'
  | 'GOOGLE';

type PlaylistProvider = 
  | 'SPOTIFY';

type ActivityProvider = 
  | 'STRAVA';

type UserConfig = {
  __typename?: 'UserConfig';
  /** Whether user playlists should be created as collaborative */
  playlistCollaborative: Scalars['Boolean'];
  /** Whether user playlists should be created as public */
  playlistPublic: Scalars['Boolean'];
  /** Whether user playlists should be created automatically */
  playlistAutoCreate: Scalars['Boolean'];
  /** Template for creating playlist description */
  playlistDescriptionTemplate: Maybe<Scalars['String']>;
  /** Template for creating playlist title */
  playlistTitleTemplate: Maybe<Scalars['String']>;
  /** Whether activity description should be updated after playlist is created */
  activityDescriptionEnabled: Scalars['Boolean'];
  /** Template for creating updated activity description that includes playlist */
  activityDescriptionTemplate: Maybe<Scalars['String']>;
};

type UserConfigInput = {
  /** Whether user playlists should be created as collaborative */
  playlistCollaborative?: Maybe<Scalars['Boolean']>;
  /** Whether user playlists should be created as public */
  playlistPublic?: Maybe<Scalars['Boolean']>;
  /** Whether user playlists should be created automatically */
  playlistAutoCreate?: Maybe<Scalars['Boolean']>;
  /** Template for creating playlist description */
  playlistDescriptionTemplate?: Maybe<Scalars['String']>;
  /** Template for creating playlist title */
  playlistTitleTemplate?: Maybe<Scalars['String']>;
  /** Whether activity description should be updated after playlist is created */
  activityDescriptionEnabled?: Maybe<Scalars['Boolean']>;
  /** Template for creating updated activity description that includes playlist */
  activityDescriptionTemplate?: Maybe<Scalars['String']>;
};

type Playlist = {
  __typename?: 'Playlist';
  playlistProviderId: Scalars['String'];
  playlistId: Scalars['String'];
  playlistUrl: Maybe<Scalars['String']>;
  playlistName: Maybe<Scalars['String']>;
  activityProviderId: Scalars['String'];
  activityId: Scalars['String'];
  activityName: Maybe<Scalars['String']>;
  activityUrl: Maybe<Scalars['String']>;
  dateCreated: Maybe<Scalars['Int']>;
};

type User = {
  __typename?: 'User';
  userId: Scalars['String'];
  email: Maybe<Scalars['String']>;
  nameFamily: Maybe<Scalars['String']>;
  nameGiven: Maybe<Scalars['String']>;
  nameDisplay: Maybe<Scalars['String']>;
  photo: Maybe<Scalars['String']>;
  providers: Array<Provider>;
};

type getCurrentUserQueryVariables = Exact<{ [key: string]: never; }>;


type getCurrentUserQuery = (
  { __typename?: 'Query' }
  & { getCurrentUser: (
    { __typename?: 'User' }
    & Pick<User, 'userId' | 'email' | 'nameFamily' | 'nameGiven' | 'nameDisplay' | 'photo'>
    & { providers: Array<(
      { __typename?: 'Provider' }
      & Pick<Provider, 'providerId' | 'name' | 'isActivityProvider' | 'isPlaylistProvider' | 'isAuthProvider'>
    )> }
  ) }
);

type deleteCurrentUserMutationVariables = Exact<{ [key: string]: never; }>;


type deleteCurrentUserMutation = (
  { __typename?: 'Mutation' }
  & { deleteCurrentUser: (
    { __typename?: 'User' }
    & Pick<User, 'userId'>
  ) }
);

type deleteCurrentUserIntegrationsMutationVariables = Exact<{
  providerIds: Array<Scalars['String']> | Scalars['String'];
}>;


type deleteCurrentUserIntegrationsMutation = (
  { __typename?: 'Mutation' }
  & { deleteCurrentUserProviders: Array<Maybe<(
    { __typename?: 'Provider' }
    & Pick<Provider, 'providerId'>
  )>> }
);

type logoutCurrentUserMutationVariables = Exact<{ [key: string]: never; }>;


type logoutCurrentUserMutation = (
  { __typename?: 'Mutation' }
  & { logoutCurrentUser: (
    { __typename?: 'User' }
    & Pick<User, 'userId'>
  ) }
);

type getAllProvidersQueryVariables = Exact<{ [key: string]: never; }>;


type getAllProvidersQuery = (
  { __typename?: 'Query' }
  & { getAllProviders: Array<(
    { __typename?: 'Provider' }
    & Pick<Provider, 'providerId' | 'name' | 'isActivityProvider' | 'isPlaylistProvider' | 'isAuthProvider'>
  )> }
);

type getCurrentUserPlaylistsQueryVariables = Exact<{ [key: string]: never; }>;


type getCurrentUserPlaylistsQuery = (
  { __typename?: 'Query' }
  & { getCurrentUserPlaylists: Array<(
    { __typename?: 'Playlist' }
    & Pick<Playlist, 'playlistProviderId' | 'playlistId' | 'playlistUrl' | 'playlistName' | 'activityProviderId' | 'activityName' | 'activityUrl' | 'dateCreated'>
  )> }
);

type getCurrentUserConfigQueryVariables = Exact<{ [key: string]: never; }>;


type getCurrentUserConfigQuery = (
  { __typename?: 'Query' }
  & { getCurrentUserConfig: (
    { __typename?: 'UserConfig' }
    & Pick<UserConfig, 'playlistCollaborative' | 'playlistPublic' | 'playlistAutoCreate' | 'playlistDescriptionTemplate' | 'playlistTitleTemplate' | 'activityDescriptionEnabled' | 'activityDescriptionTemplate'>
  ) }
);

type updateCurrentUserConfigMutationVariables = Exact<{
  userConfigInput: UserConfigInput;
}>;


type updateCurrentUserConfigMutation = (
  { __typename?: 'Mutation' }
  & { updateCurrentUserConfig: (
    { __typename?: 'UserConfig' }
    & Pick<UserConfig, 'playlistCollaborative' | 'playlistPublic' | 'playlistAutoCreate' | 'playlistDescriptionTemplate' | 'playlistTitleTemplate' | 'activityDescriptionEnabled' | 'activityDescriptionTemplate'>
  ) }
);


 const getCurrentUserDocument = gql`
    query getCurrentUser {
  getCurrentUser {
    userId
    email
    nameFamily
    nameGiven
    nameDisplay
    photo
    providers {
      providerId
      name
      isActivityProvider
      isPlaylistProvider
      isAuthProvider
    }
  }
}
    `;
 const deleteCurrentUserDocument = gql`
    mutation deleteCurrentUser {
  deleteCurrentUser {
    userId
  }
}
    `;
 const deleteCurrentUserIntegrationsDocument = gql`
    mutation deleteCurrentUserIntegrations($providerIds: [String!]!) {
  deleteCurrentUserProviders(providerIds: $providerIds) {
    providerId
  }
}
    `;
 const logoutCurrentUserDocument = gql`
    mutation logoutCurrentUser {
  logoutCurrentUser {
    userId
  }
}
    `;
 const getAllProvidersDocument = gql`
    query getAllProviders {
  getAllProviders {
    providerId
    name
    isActivityProvider
    isPlaylistProvider
    isAuthProvider
  }
}
    `;
 const getCurrentUserPlaylistsDocument = gql`
    query getCurrentUserPlaylists {
  getCurrentUserPlaylists {
    playlistProviderId
    playlistId
    playlistUrl
    playlistName
    activityProviderId
    activityName
    activityUrl
    dateCreated
  }
}
    `;
 const getCurrentUserConfigDocument = gql`
    query getCurrentUserConfig {
  getCurrentUserConfig {
    playlistCollaborative
    playlistPublic
    playlistAutoCreate
    playlistDescriptionTemplate
    playlistTitleTemplate
    activityDescriptionEnabled
    activityDescriptionTemplate
  }
}
    `;
 const updateCurrentUserConfigDocument = gql`
    mutation updateCurrentUserConfig($userConfigInput: UserConfigInput!) {
  updateCurrentUserConfig(userConfigInput: $userConfigInput) {
    playlistCollaborative
    playlistPublic
    playlistAutoCreate
    playlistDescriptionTemplate
    playlistTitleTemplate
    activityDescriptionEnabled
    activityDescriptionTemplate
  }
}
    `;
export interface ProviderOptions {
  __typename?: 'Provider';
  providerId?: Provider['providerId'];
  name?: Provider['name'];
  isAuthProvider?: Provider['isAuthProvider'];
  isActivityProvider?: Provider['isActivityProvider'];
  isPlaylistProvider?: Provider['isPlaylistProvider'];
}

export function newProvider(
  options: ProviderOptions = {},
  cache: Record<string, any> = {}
): Provider {
  const o = (cache['Provider'] = {} as Provider);
  o.__typename = 'Provider';
  o.providerId = options.providerId ?? 'providerId';
  o.name = options.name ?? 'name';
  o.isAuthProvider = options.isAuthProvider ?? false;
  o.isActivityProvider = options.isActivityProvider ?? false;
  o.isPlaylistProvider = options.isPlaylistProvider ?? false;
  return o;
}

function maybeNewProvider(
  value: ProviderOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false
): Provider {
  if (value === undefined) {
    return isSet ? undefined : cache['Provider'] || newProvider({}, cache);
  } else if (value.__typename) {
    return value as Provider;
  } else {
    return newProvider(value, cache);
  }
}

function maybeNewOrNullProvider(
  value: ProviderOptions | undefined | null,
  cache: Record<string, any>
): Provider | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as Provider;
  } else {
    return newProvider(value, cache);
  }
}
export interface UserConfigOptions {
  __typename?: 'UserConfig';
  playlistCollaborative?: UserConfig['playlistCollaborative'];
  playlistPublic?: UserConfig['playlistPublic'];
  playlistAutoCreate?: UserConfig['playlistAutoCreate'];
  playlistDescriptionTemplate?: UserConfig['playlistDescriptionTemplate'];
  playlistTitleTemplate?: UserConfig['playlistTitleTemplate'];
  activityDescriptionEnabled?: UserConfig['activityDescriptionEnabled'];
  activityDescriptionTemplate?: UserConfig['activityDescriptionTemplate'];
}

export function newUserConfig(
  options: UserConfigOptions = {},
  cache: Record<string, any> = {}
): UserConfig {
  const o = (cache['UserConfig'] = {} as UserConfig);
  o.__typename = 'UserConfig';
  o.playlistCollaborative = options.playlistCollaborative ?? false;
  o.playlistPublic = options.playlistPublic ?? false;
  o.playlistAutoCreate = options.playlistAutoCreate ?? false;
  o.playlistDescriptionTemplate = options.playlistDescriptionTemplate ?? null;
  o.playlistTitleTemplate = options.playlistTitleTemplate ?? null;
  o.activityDescriptionEnabled = options.activityDescriptionEnabled ?? false;
  o.activityDescriptionTemplate = options.activityDescriptionTemplate ?? null;
  return o;
}

function maybeNewUserConfig(
  value: UserConfigOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false
): UserConfig {
  if (value === undefined) {
    return isSet ? undefined : cache['UserConfig'] || newUserConfig({}, cache);
  } else if (value.__typename) {
    return value as UserConfig;
  } else {
    return newUserConfig(value, cache);
  }
}

function maybeNewOrNullUserConfig(
  value: UserConfigOptions | undefined | null,
  cache: Record<string, any>
): UserConfig | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as UserConfig;
  } else {
    return newUserConfig(value, cache);
  }
}
export interface PlaylistOptions {
  __typename?: 'Playlist';
  playlistProviderId?: Playlist['playlistProviderId'];
  playlistId?: Playlist['playlistId'];
  playlistUrl?: Playlist['playlistUrl'];
  playlistName?: Playlist['playlistName'];
  activityProviderId?: Playlist['activityProviderId'];
  activityId?: Playlist['activityId'];
  activityName?: Playlist['activityName'];
  activityUrl?: Playlist['activityUrl'];
  dateCreated?: Playlist['dateCreated'];
}

export function newPlaylist(
  options: PlaylistOptions = {},
  cache: Record<string, any> = {}
): Playlist {
  const o = (cache['Playlist'] = {} as Playlist);
  o.__typename = 'Playlist';
  o.playlistProviderId = options.playlistProviderId ?? 'playlistProviderId';
  o.playlistId = options.playlistId ?? 'playlistId';
  o.playlistUrl = options.playlistUrl ?? null;
  o.playlistName = options.playlistName ?? null;
  o.activityProviderId = options.activityProviderId ?? 'activityProviderId';
  o.activityId = options.activityId ?? 'activityId';
  o.activityName = options.activityName ?? null;
  o.activityUrl = options.activityUrl ?? null;
  o.dateCreated = options.dateCreated ?? null;
  return o;
}

function maybeNewPlaylist(
  value: PlaylistOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false
): Playlist {
  if (value === undefined) {
    return isSet ? undefined : cache['Playlist'] || newPlaylist({}, cache);
  } else if (value.__typename) {
    return value as Playlist;
  } else {
    return newPlaylist(value, cache);
  }
}

function maybeNewOrNullPlaylist(
  value: PlaylistOptions | undefined | null,
  cache: Record<string, any>
): Playlist | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as Playlist;
  } else {
    return newPlaylist(value, cache);
  }
}
export interface UserOptions {
  __typename?: 'User';
  userId?: User['userId'];
  email?: User['email'];
  nameFamily?: User['nameFamily'];
  nameGiven?: User['nameGiven'];
  nameDisplay?: User['nameDisplay'];
  photo?: User['photo'];
  providers?: Array<ProviderOptions>;
}

export function newUser(options: UserOptions = {}, cache: Record<string, any> = {}): User {
  const o = (cache['User'] = {} as User);
  o.__typename = 'User';
  o.userId = options.userId ?? 'userId';
  o.email = options.email ?? null;
  o.nameFamily = options.nameFamily ?? null;
  o.nameGiven = options.nameGiven ?? null;
  o.nameDisplay = options.nameDisplay ?? null;
  o.photo = options.photo ?? null;
  o.providers = (options.providers ?? []).map((i) =>
    maybeNewProvider(i, cache, options.hasOwnProperty('providers'))
  );
  return o;
}

function maybeNewUser(
  value: UserOptions | undefined,
  cache: Record<string, any>,
  isSet: boolean = false
): User {
  if (value === undefined) {
    return isSet ? undefined : cache['User'] || newUser({}, cache);
  } else if (value.__typename) {
    return value as User;
  } else {
    return newUser(value, cache);
  }
}

function maybeNewOrNullUser(
  value: UserOptions | undefined | null,
  cache: Record<string, any>
): User | null {
  if (!value) {
    return null;
  } else if (value.__typename) {
    return value as User;
  } else {
    return newUser(value, cache);
  }
}
let nextFactoryIds: Record<string, number> = {};

export function resetFactoryIds() {
  nextFactoryIds = {};
}

function nextFactoryId(objectName: string): string {
  const nextId = nextFactoryIds[objectName] || 1;
  nextFactoryIds[objectName] = nextId + 1;
  return String(nextId);
}

interface getCurrentUserDataOptions {
  getCurrentUser?: UserOptions;
}

export function newgetCurrentUserData(data: getCurrentUserDataOptions) {
  return {
    __typename: 'Query' as const,
    getCurrentUser: maybeNewUser(data['getCurrentUser'] || undefined, {}),
  };
}

export function newgetCurrentUserResponse(
  data: getCurrentUserDataOptions | Error
): MockedResponse<getCurrentUserQueryVariables, getCurrentUserQuery> {
  return {
    request: { query: getCurrentUserDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: { data: data instanceof Error ? undefined : (newgetCurrentUserData(data) as any) },
    error: data instanceof Error ? data : undefined,
  };
}
interface deleteCurrentUserDataOptions {
  deleteCurrentUser?: UserOptions;
}

export function newdeleteCurrentUserData(data: deleteCurrentUserDataOptions) {
  return {
    __typename: 'Mutation' as const,
    deleteCurrentUser: maybeNewUser(data['deleteCurrentUser'] || undefined, {}),
  };
}

export function newdeleteCurrentUserResponse(
  data: deleteCurrentUserDataOptions | Error
): MockedResponse<deleteCurrentUserMutationVariables, deleteCurrentUserMutation> {
  return {
    request: { query: deleteCurrentUserDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: { data: data instanceof Error ? undefined : (newdeleteCurrentUserData(data) as any) },
    error: data instanceof Error ? data : undefined,
  };
}
interface deleteCurrentUserIntegrationsDataOptions {
  deleteCurrentUserProviders?: ProviderOptions[];
}

export function newdeleteCurrentUserIntegrationsData(
  data: deleteCurrentUserIntegrationsDataOptions
) {
  return {
    __typename: 'Mutation' as const,
    deleteCurrentUserProviders:
      data['deleteCurrentUserProviders']?.map((d) => newProvider(d)) || [],
  };
}

export function newdeleteCurrentUserIntegrationsResponse(
  variables: deleteCurrentUserIntegrationsMutationVariables,
  data: deleteCurrentUserIntegrationsDataOptions | Error
): MockedResponse<
  deleteCurrentUserIntegrationsMutationVariables,
  deleteCurrentUserIntegrationsMutation
> {
  return {
    request: { query: deleteCurrentUserIntegrationsDocument, variables },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: {
      data: data instanceof Error ? undefined : (newdeleteCurrentUserIntegrationsData(data) as any),
    },
    error: data instanceof Error ? data : undefined,
  };
}
interface logoutCurrentUserDataOptions {
  logoutCurrentUser?: UserOptions;
}

export function newlogoutCurrentUserData(data: logoutCurrentUserDataOptions) {
  return {
    __typename: 'Mutation' as const,
    logoutCurrentUser: maybeNewUser(data['logoutCurrentUser'] || undefined, {}),
  };
}

export function newlogoutCurrentUserResponse(
  data: logoutCurrentUserDataOptions | Error
): MockedResponse<logoutCurrentUserMutationVariables, logoutCurrentUserMutation> {
  return {
    request: { query: logoutCurrentUserDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: { data: data instanceof Error ? undefined : (newlogoutCurrentUserData(data) as any) },
    error: data instanceof Error ? data : undefined,
  };
}
interface getAllProvidersDataOptions {
  getAllProviders?: ProviderOptions[];
}

export function newgetAllProvidersData(data: getAllProvidersDataOptions) {
  return {
    __typename: 'Query' as const,
    getAllProviders: data['getAllProviders']?.map((d) => newProvider(d)) || [],
  };
}

export function newgetAllProvidersResponse(
  data: getAllProvidersDataOptions | Error
): MockedResponse<getAllProvidersQueryVariables, getAllProvidersQuery> {
  return {
    request: { query: getAllProvidersDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: { data: data instanceof Error ? undefined : (newgetAllProvidersData(data) as any) },
    error: data instanceof Error ? data : undefined,
  };
}
interface getCurrentUserPlaylistsDataOptions {
  getCurrentUserPlaylists?: PlaylistOptions[];
}

export function newgetCurrentUserPlaylistsData(data: getCurrentUserPlaylistsDataOptions) {
  return {
    __typename: 'Query' as const,
    getCurrentUserPlaylists: data['getCurrentUserPlaylists']?.map((d) => newPlaylist(d)) || [],
  };
}

export function newgetCurrentUserPlaylistsResponse(
  data: getCurrentUserPlaylistsDataOptions | Error
): MockedResponse<getCurrentUserPlaylistsQueryVariables, getCurrentUserPlaylistsQuery> {
  return {
    request: { query: getCurrentUserPlaylistsDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: {
      data: data instanceof Error ? undefined : (newgetCurrentUserPlaylistsData(data) as any),
    },
    error: data instanceof Error ? data : undefined,
  };
}
interface getCurrentUserConfigDataOptions {
  getCurrentUserConfig?: UserConfigOptions;
}

export function newgetCurrentUserConfigData(data: getCurrentUserConfigDataOptions) {
  return {
    __typename: 'Query' as const,
    getCurrentUserConfig: maybeNewUserConfig(data['getCurrentUserConfig'] || undefined, {}),
  };
}

export function newgetCurrentUserConfigResponse(
  data: getCurrentUserConfigDataOptions | Error
): MockedResponse<getCurrentUserConfigQueryVariables, getCurrentUserConfigQuery> {
  return {
    request: { query: getCurrentUserConfigDocument },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: {
      data: data instanceof Error ? undefined : (newgetCurrentUserConfigData(data) as any),
    },
    error: data instanceof Error ? data : undefined,
  };
}
interface updateCurrentUserConfigDataOptions {
  updateCurrentUserConfig?: UserConfigOptions;
}

export function newupdateCurrentUserConfigData(data: updateCurrentUserConfigDataOptions) {
  return {
    __typename: 'Mutation' as const,
    updateCurrentUserConfig: maybeNewUserConfig(data['updateCurrentUserConfig'] || undefined, {}),
  };
}

export function newupdateCurrentUserConfigResponse(
  variables: updateCurrentUserConfigMutationVariables,
  data: updateCurrentUserConfigDataOptions | Error
): MockedResponse<updateCurrentUserConfigMutationVariables, updateCurrentUserConfigMutation> {
  return {
    request: { query: updateCurrentUserConfigDocument, variables },
    // TODO Remove the any by having interfaces have a __typename that pacifies mutation type unions
    result: {
      data: data instanceof Error ? undefined : (newupdateCurrentUserConfigData(data) as any),
    },
    error: data instanceof Error ? data : undefined,
  };
}

  export type MockedResponse<V, Q> = {
    request: {
      query: any;
      variables?: V;
    };
    result: {
      data?: Q;
    };
    error?: Error;
    // Note this only works if using Homebound's better-apollo-mocked-provider
    requestedCount?: number;
  };
