/* eslint-disable */
/* This file is autogenerated, see codegen.yml */
export const namedOperations = {
  Query: {
    getCurrentUser: 'getCurrentUser'
  }
}
// Generated on 2021-01-24T16:49:41+00:00
