/* eslint-disable */
/* This file is autogenerated, see codegen.yml */
export const namedOperations = {
  Query: {
    getCurrentUser: 'getCurrentUser'
  },
  Mutation: {
    deleteCurrentUser: 'deleteCurrentUser',
    deleteCurrentUserIntegrations: 'deleteCurrentUserIntegrations',
    logoutCurrentUser: 'logoutCurrentUser'
  }
}
// Generated on 2021-01-27T22:56:54+00:00
