openapi: 3.0.1
info:
  title: moovin-groovin (auth)
  description: Server for integrating Strava API with Spotify API (Auth endpoints)
  version: 1.0.0
paths:
  /login:
    get:
      description: Auth user against third party OAuth
      parameters:
        - $ref: '#/components/parameters/RedirectUrlParam'
        - $ref: '#/components/parameters/StateParam'
      responses:
        302:
          description: Redirects to auth URL
  /callback:
    get:
      description: Handle user auth
      parameters:
        - $ref: '#/components/parameters/CodeParam'
        - $ref: '#/components/parameters/ScopeParam'
        - $ref: '#/components/parameters/StateParam'
        - $ref: '#/components/parameters/ErrorParam'
        - $ref: '#/components/parameters/ErrorCodeParam'
        - $ref: '#/components/parameters/ErrorDescriptionParam'
        - $ref: '#/components/parameters/ErrorReasonParam'
        - $ref: '#/components/parameters/RedirectUrlParam'
        - $ref: '#/components/parameters/AuthUserParam'
        - $ref: '#/components/parameters/PromptParam'
      responses:
        200:
          description: Error or success message
        302:
          description: Redirects to 'redirect_uri' if it provided and valid
components:
  parameters:
    CodeParam:
      name: code
      in: query
      required: false
      schema:
        type: string
    ScopeParam:
      name: scope
      in: query
      required: false
      allowReserved: true
      schema:
        type: string
    StateParam:
      name: state
      in: query
      allowEmptyValue: true
      required: false
      schema:
        type: string
    ErrorParam:
      name: error
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: string    
    ErrorCodeParam:
      name: error_code
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: string    
    ErrorDescriptionParam:
      name: error_description
      in: query
      allowEmptyValue: false
      required: false
      allowReserved: true
      schema:
        type: string    
    ErrorReasonParam:
      name: error_reason
      in: query
      allowEmptyValue: false
      required: false
      schema:
        type: string    
    RedirectUrlParam:
      name: redirect_url
      in: query
      allowReserved: false
      allowEmptyValue: true
      required: false
      schema:
        type: string
    AuthUserParam:
      name: authuser
      in: query
      allowReserved: false
      allowEmptyValue: false
      required: false
      schema:
        type: string
    PromptParam:
      name: prompt
      in: query
      allowReserved: false
      allowEmptyValue: false
      required: false
      schema:
        type: string
